### ISSUE TITLE
Adaptação do CSS SciELO para multilíngua

### ISSUE THREAD

**Issue by jorgesallum** [jorgesallum/SciELO-EdO#14]
O CSS fornecido pelo SciELO teve de ser refeito para receber ambiente multilíngua. Foram ajustes no código e no texto. 

 - [x] Tornar ambiente multiíngua
 - [x] Refazer CSS

**Comment by amandasramalho** [comment]
Entrei agora no site e possui sim os links para as interfaces em Inglês e Espanhol. Aparentemente estão funcionando porém, quando entramos nas interfaces em EN ou ES, não possui a opção de voltar à interface em PT.

**Comment by amandasramalho** [comment]
@jorgesallum Vou fechar este ticket validando as alterações realizadas no CSS para contemplar as interfaces em Inglês e Espanhol, porém, novos ajustes deverão ser acordados antes da efetiva aplicação. Neste caso o CSS foi encaminhado pelo SciELO e deveríamos também ter feito a solicitação do ambiente multilíngua. Fica pendente apenas o ajuste para voltar à interface em PT, que será aberto em outro ticket.
