### ISSUE TITLE
Inclusão de textos traduzidos nas interfaces multilíngua da Home

### ISSUE THREAD

**Issue by jorgesallum** [jorgesallum/SciELO-EdO#15]
Tradução dos textos da Home para inglês e espanhol

**Comment by amandasramalho** [comment]
Jorge, posso providenciar por aqui as traduções oficiais da plataforma, mas poderíamos deixar esta implementação para outras entregas, caso os textos originais venham a ter atualizações. Assim já traduziríamos a parte interna também (que está sendo remodelada ainda) e não somente a Home.

**Comment by jorgesallum** [comment]
Amanda, considere que a primeira tradução foi apenas um esboço para aquele encontro. Acho sim que podemos deixar para frente. Eu vou criar no último release um card amplo chamado "Traduções e localizações"

**Comment by amandasramalho** [comment]
@jorgesallum Estou fechando este ticket tendo em vista que as traduções foram previamente incorporadas. Porém, novas traduções serão fornecidas pelo SciELO. Quando fecharmos o texto oficial da home, reabro este ticket para que eles sejam apenas atualizados.
