### ISSUE TITLE
Criação de ambiente para desenvolvimento do SciELO EDO com base no ambiente Livro-da-classe

### ISSUE THREAD

**Issue by jorgesallum** [jorgesallum/SciELO-EdO#16]
Interface com opções de recebimento de word, estruturação de metadados, edição de texto importado e botões para gerar PDF.

**Comment by amandasramalho** [comment]
O ambiente foi criado na URL http://editorial.hedra.com.br/, o acesso foi realizado via login e senha previamente cadastrados e possui as opções básicas para envio de arquivo e edição de metadados. Outras sugestões serão encaminhadas via tickets.
