### ISSUE TITLE
Desenvolvimento de importação de docx a partir da aba "Dados do livro"

### ISSUE THREAD

**Issue by jorgesallum** [jorgesallum/SciELO-EdO#17]
A aplicação recebia somente arquivos docx criados pelo Openoffice. Agora recebe de word microsoft e googledocs.

**Comment by amandasramalho** [comment]
Foi realizado um teste de importação de texto em docx. No teste realizado haviam bullets, citação e notas. 
O carregamento foi 100% concluído e na visualização e área de edição de texto os elementos mencionados acima foram identificados pela plataforma. 
Anexo modelo de arquivo utilizado. 
[Capitulo.docx](https://github.com/jorgesallum/SciELO-EdO/files/476933/Capitulo.docx)

Identificação do título:
![image](https://cloud.githubusercontent.com/assets/5446933/18587664/798ca4d4-7bf9-11e6-81b6-25bd29517676.png)

Citação:
![image](https://cloud.githubusercontent.com/assets/5446933/18587669/81ffd73a-7bf9-11e6-974a-4ef57e655115.png)

Bullets
![image](https://cloud.githubusercontent.com/assets/5446933/18587684/9fe948e4-7bf9-11e6-887e-58ddfa7267ac.png)

Notas reunidas no final do capítulo
![image](https://cloud.githubusercontent.com/assets/5446933/18587705/af26a50e-7bf9-11e6-9ed4-08acb8b0691a.png)

Os próximos testes serão com arquivos que contenham tabelas e imagens.

**Comment by jorgesallum** [comment]
Amanda, por favor atente para o fato de que as entregas da função de importação de tabelas e imagens estão em releases futuros!
