### ISSUE TITLE
Inclusão de opções avançadas 

### ISSUE THREAD

**Issue by jorgesallum** [jorgesallum/SciELO-EdO#18]
Nesta área serão incluídas algumas ações para customização do template. Como parte inicial, nesta área foram incluídas opções de remoção de sumário e notas de fim.
As descrições detalhadas estão nos tickets:
Remoção de sumário - #24 
Notas de fim - #23

**Comment by amandasramalho** [comment]
Tenho o mesmo comentário que o ticket #19 , o ideal seria que estes tópicos estivessem em tickets independentes. Da forma que ele está, o ticket #18 e #19 estão praticamente iguais e referem-se ao mesmo problema. Precisamos evitar ao máximo duplicidade de tópicos.

**Comment by jorgesallum** [comment]
@amandasramalho vou corrigir isso amanhã e resolver os problemas até terça.

**Comment by amandasramalho** [comment]
Entrei no sistema e a área foi criada com os dois tópicos iniciais. Esta área pode sofrer alterações conforme as demandas de customizações.
![image](https://cloud.githubusercontent.com/assets/5446933/18674465/b6d51504-7f25-11e6-84e6-c0c6c2815fc7.png)
