### ISSUE TITLE
Produção de vídeo tutorial para apresentação

### ISSUE THREAD

**Issue by jorgesallum** [jorgesallum/SciELO-EdO#20]
Produção de vídeo atual para reunião de conselho.

**Comment by amandasramalho** [comment]
Jorge, em nossa última reunião havíamos concordado que o vídeo tratava-se de uma apresentação interna realizada pela sua equipe para explicar alguns processos, mas que não caracterizava-se como uma entrega. Poderíamos considerar futuramente a produção de um vídeo quando o sistema já estivesse com o Layout e serviços definidos, uma vez que à cada atualização, o vídeo ficaria desatualizado.

**Comment by jorgesallum** [comment]
Eu vou colocar em um release futuro então e descartar esse.
