### ISSUE TITLE
Criação de templates SciELO provisórios para demostração

### ISSUE THREAD

**Issue by jorgesallum** [jorgesallum/SciELO-EdO#21]
Criação de cinco templates com formatos diferentes, logo do SciELO, créditos e colofon para testes.

**Comment by amandasramalho** [comment]
Jorge, ao invés de criar 5 de uma vez não seria melhor criar 1 bem montado e depois geraríamos os outros como complementares de um modelo consolidado?

**Comment by jorgesallum** [comment]
Essa descrição é do que foi entregue. Sim, seria melhor. Na ocasião não tínhamos o template. Está previsto para o 2.1.1

**Comment by amandasramalho** [comment]
O template foi testado, tenho alguns comentários:
-- Eliminar excesso de hifenização;
-- Excesso de espaço entre a marca de corte e o início do texto (o texto está muito comprimido);
-- A citação não aparece diagramada corretamente como citação;
-- As URLs estão sem quebra, ultrapassam as linhas de diagramação e de corte.

**Comment by jorgesallum** [comment]
Amanda, eliminei os excessos de hifenização e os problemas com URLs. 

Quanto à citação, que não foi convertida, pediria para abrir um chamado ligado ao próximo release, com Label = Bug

Já sobre os espaços, entendo que isso é uma adequação de template e deve estar ligado ao novo template. 

Fechamos o release!

**Comment by jorgesallum** [comment]
http://editorial.hedra.com.br/books/dt-SciELO16AnosdeAcessoAberto-scielo-91/LIVRO.pdf

**Comment by jorgesallum** [comment]
@amandasramalho deixei aqui para vc testar e fechar. É o último!

**Comment by amandasramalho** [comment]
@jorgesallum 
Fiz também um teste e Ok quanto à hifenização e quebra das URLs!
