### ISSUE TITLE
 Novo fluxo para recebimento de PDF (Notificações)

### ISSUE THREAD

**Issue by jorgesallum** [jorgesallum/SciELO-EdO#8]
Atualmente é preciso esperar até que o sistema gere o PDF. Isso pode demorar até alguns minutos. A intenção é evitar a sensação de espera. Teríamos um ícone como um sino no lado superior direito que envia mensagens. Assim, quando o sistema apresentar um PDF disponível, é gerada uma mensagem e um link nessa área.

**Comment by amandasramalho** [comment]
Oi Jorge, poderia explicar melhor sobre este ticket?

**Comment by jorgesallum** [comment]
@amandasramalho Incorporamos essa feature em outra tarefa. Favor desconsiderar.
